# -*- coding: utf-8 -*-
"""Future_DS3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HAd1sp6sr3YxieBSCoyYkYEbSi4T5swe

#Analyze marketing and lead funnel data to understand how users move from
#visitors → leads → customers.

Dataset Used: Nykaa Marketing Campaign Performance Dataset;
Real-World Inspired E-commerce Campaign Data for Marketing Analytics & ROI.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load data
df = pd.read_csv('nykaa_campaign_data.csv')
df.head()

# 1. Aggregate funnel volumes
funnel_data = {
    'Stage': ['Impressions', 'Clicks', 'Leads', 'Conversions'],
    'Value': [
        df['Impressions'].sum(),
        df['Clicks'].sum(),
        df['Leads'].sum(),
        df['Conversions'].sum()
    ]
}

funnel_df = pd.DataFrame(funnel_data)

"""#Users dropping off in the funnel"""



# 2. Calculate Retention and Drop-off Rates
# Retention rate is the % of the PREVIOUS stage that reached the CURRENT stage
funnel_df['Retention_Rate'] = 100.0
for i in range(1, len(funnel_df)):
    funnel_df.loc[i, 'Retention_Rate'] = (funnel_df.loc[i, 'Value'] / funnel_df.loc[i-1, 'Value']) * 100

# Drop-off rate is 100 - Retention rate (for stages after the first)
funnel_df['Drop_off_Rate'] = 0.0
for i in range(1, len(funnel_df)):
    funnel_df.loc[i, 'Drop_off_Rate'] = 100 - funnel_df.loc[i, 'Retention_Rate']

# ANSI escape codes
BOLD = '\033[1m'
RED = '\033[91m'
END = '\033[0m'
# 3. Print the metrics
print(f"             --- {BOLD}Funnel Drop-off Analysis{END} ---")
funnel_df

# 4. Identify the biggest drop-off
max_drop_idx = funnel_df['Drop_off_Rate'].idxmax()
# Update your print statement like this:
print(f"{BOLD}Biggest Drop-off Stage: {BOLD}{RED}{funnel_df.loc[max_drop_idx, 'Stage']} "
      f"(Lost {funnel_df.loc[max_drop_idx, 'Drop_off_Rate']:.2f}% of users){END}")

# 5. Visualization: Funnel and Drop-off
plt.figure(figsize=(12, 6))

# Subplot 1: Funnel Volume
plt.subplot(1, 2, 1)
sns.barplot(data=funnel_df, x='Stage', y='Value',hue='Stage', palette='Blues_d')
plt.title('Funnel Volume (Total Counts)')
plt.ylabel('Count')

# Subplot 2: Drop-off Rate
plt.subplot(1, 2, 2)
sns.barplot(data=funnel_df[1:], x='Stage', y='Drop_off_Rate',hue='Stage', palette='Reds_d')
plt.title('Drop-off Rate per Stage (%)')
plt.ylabel('Percentage Lost (%)')

plt.tight_layout()
plt.savefig('dropoff_analysis_viz.png')

# Save the detailed stats to CSV
funnel_df.to_csv('detailed_dropoff_stats.csv', index=False)

# 2. Calculate Drop-off and Retention Rates
funnel_df['Retention_Rate'] = 100.0
funnel_df['Drop_off_Rate'] = 0.0

for i in range(1, len(funnel_df)):
    prev_val = funnel_df.loc[i-1, 'Value']
    curr_val = funnel_df.loc[i, 'Value']

    retention = (curr_val / prev_val) * 100
    funnel_df.loc[i, 'Retention_Rate'] = retention
    funnel_df.loc[i, 'Drop_off_Rate'] = 100 - retention

# 3. Create the Funnel Plot
plt.figure(figsize=(10, 7))

# To center the bars, we can calculate an offset
max_val = funnel_df['Value'].max()
funnel_df['Left_Offset'] = (max_val - funnel_df['Value']) / 2

# Plot using barh
plt.barh(funnel_df['Stage'][::-1], funnel_df['Value'][::-1], left=funnel_df['Left_Offset'][::-1], color=sns.color_palette("RdYlGn_r", 4))

# Add data labels
for i, (val, stage, drop) in enumerate(zip(funnel_df['Value'], funnel_df['Stage'], funnel_df['Drop_off_Rate'])):
    # Calculate text position
    label_text = f"{val:,}"
    if i > 0:
        label_text += f"\n(Drop: {drop:.1f}%)"

    # We plot backwards so indices are flipped for labels
    plt.text(max_val/2, 3-i, label_text, ha='center', va='center', color='black', fontweight='bold', fontsize=10)

plt.title('Marketing Funnel: Impressions to Conversions', fontsize=15)
plt.xlabel('Volume')
plt.tight_layout()
plt.savefig('marketing_funnel_chart.png')

# 4. Display the results table
print("--- Funnel Analysis Summary ---")
print(funnel_df[['Stage', 'Value', 'Retention_Rate', 'Drop_off_Rate']])

"""#Key Finding: "leakiest" stage is the initial engagement. Over 91% of people who see the campaign do not click on it. However, once a user clicks, they are very likely to become a lead and eventually a customer.

#Channels bringing high-quality leads
"""

# Define 'High Quality' as high Lead-to-Conversion rate and high ROI
channel_quality = df.groupby('Campaign_Type').agg({
    'Leads': 'sum',
    'Conversions': 'sum',
    'Revenue': 'sum',
    'ROI': 'mean',
    'Acquisition_Cost': 'mean'
}).reset_index()

# Calculate Metrics
channel_quality['Lead_to_Conv_Rate'] = (channel_quality['Conversions'] / channel_quality['Leads']) * 100
channel_quality['Revenue_per_Lead'] = channel_quality['Revenue'] / channel_quality['Leads']

# Sort by Conversion Rate to see quality
channel_quality = channel_quality.sort_values(by='Lead_to_Conv_Rate', ascending=False)

print(f"               ---{BOLD} Channel Quality Analysis {END}---")
print(channel_quality[['Campaign_Type', 'Lead_to_Conv_Rate', 'ROI', 'Revenue_per_Lead']])

# Visualization 1: Lead to Conversion Rate
plt.figure(figsize=(12, 6))
ax3 = sns.barplot(data=channel_quality, x='Campaign_Type', y='Lead_to_Conv_Rate', hue='Campaign_Type', palette='viridis', legend=False)
for containers in ax3.containers:
    ax3.bar_label(containers, fmt='%.2f%%', padding=3)
plt.title('Lead-to-Conversion Rate by Channel (%)')

# Visualization 2: ROI by Channel
plt.figure(figsize=(12, 6))
roi_data = channel_quality.sort_values('ROI', ascending=False)
ax4 = sns.barplot(data=roi_data, x='Campaign_Type', y='ROI', hue='Campaign_Type', palette='magma', legend=False)
for containers in ax4.containers:
    ax4.bar_label(containers, fmt='%.2f', padding=3)
plt.title('Financial Quality: Average ROI by Channel')

plt.tight_layout()
plt.show()

"""#Traffic-to-lead conversion"""

# Calculate Click-to-Lead Rate (Traffic-to-Lead)
df['Traffic_to_Lead_Rate'] = (df['Leads'] / df['Clicks']) * 100

# 1. Traffic-to-Lead by Channel
traffic_lead_channel = df.groupby('Campaign_Type')['Traffic_to_Lead_Rate'].mean().reset_index().sort_values(by='Traffic_to_Lead_Rate', ascending=False)

# 2. Traffic-to-Lead by Target Audience
traffic_lead_audience = df.groupby('Target_Audience')['Traffic_to_Lead_Rate'].mean().reset_index().sort_values(by='Traffic_to_Lead_Rate', ascending=False)

# 3. Traffic-to-Lead by Language
traffic_lead_lang = df.groupby('Language')['Traffic_to_Lead_Rate'].mean().reset_index().sort_values(by='Traffic_to_Lead_Rate', ascending=False)

# Plotting
plt.figure(figsize=(18, 5))

# Plot 1: Channel
plt.subplot(1, 3, 1)
ax1 = sns.barplot(data=traffic_lead_channel, y='Campaign_Type', x='Traffic_to_Lead_Rate',hue='Campaign_Type', palette='viridis', legend=False)
plt.title('Traffic-to-Lead by Channel (%)')
plt.yticks(rotation=0)
plt.xlabel('Rate (%)')
for container in ax1.containers:
    ax1.bar_label(container, fmt='%.2f')

# Plot 2: Audience
plt.subplot(1, 3, 2)
ax2 = sns.barplot(data=traffic_lead_audience, y='Target_Audience', x='Traffic_to_Lead_Rate', hue='Target_Audience', palette='magma', legend=False)
plt.title('Traffic-to-Lead by Audience (%)')
plt.yticks(rotation=0)
plt.xlabel('Rate (%)')
for container in ax2.containers:
    ax2.bar_label(container, fmt='%.2f')

# Plot 3: Language
plt.subplot(1, 3, 3)
ax3 = sns.barplot(data=traffic_lead_lang, y='Language', x='Traffic_to_Lead_Rate', hue='Language', palette='coolwarm', legend=False)
plt.title('Traffic-to-Lead by Language (%)')
plt.yticks(rotation=0)
plt.xlabel('Rate (%)')
for container in ax3.containers:
    ax3.bar_label(container, fmt='%.2f')

plt.tight_layout()
plt.savefig('traffic_to_lead_detailed.png')